### ISSUE TITLE
[Task] Upgrade ESN Sabre to Php 7.4

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#461]
# Definition

Update ESN Sabre Php version to 7.4

To upgrade to Php 7.4, we need to update to Php-7.4-compliant dependencies including latest Sabre version.

# Tasks

* [ ] Update Sabre/DAV dependency (4.1.5)
* [ ] Rebase ESN VObject lib to the latest version (4.3.5)
* [ ] Update standard dependencies to the latest version
* [ ] Upgrage PhpUnit version
* [ ] Upgrade coding style according to [PSR-2](https://www.php-fig.org/psr/psr-2/)
* [ ] Update linters
