### ISSUE TITLE
[TASK][Notification component] Bootstraping the notification component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#497]
#### Prerequisites

This issue must be started after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496

#### Subtasks

- [ ] Create a new repository in https://github.com/linagora to store all the Web Components for Calendar/Contacts. We can call it something like `tcal-wc` or `tcal-components`. **Do not create another one if the repository already exists.**
- [ ] Set up a building process using the chosen framework/library with a "Hello World" component (remember to have an npm's `postinstall` script to build after installing).
- [ ] Make sure the "Hello World" component is work in any SPA.

**Comment by renaudboyer** [comment]
For now, we'll create a single repo for the compoent

**Comment by huy-ta** [comment]
Here's the repo: https://github.com/huy-ta/calendar-next-gen. The repo will be moved to the approriate organization later.
