### ISSUE TITLE
[TASK][Notification component] Build the event notification popover component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#498]
#### Prerequisites

Must be done after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/497

#### Subtasks

- [ ] The web component's name can be something like `tcal-event-notification-popover`.
- [ ] The web component will only comprise the popover, not the alarm/notification button.
- [ ] Build a web component with only "placeholder" texts that follow the design in [the story](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/450):

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/4e1c1c3b-1e69-48f6-bcec-e4e96b26614f)

- [ ] Then enable the component to take in an array of events that are partially structured like [this](https://github.com/linagora/dav-parser/blob/main/src/types/dav-parser.d.ts#L1) and display the events.
- [ ] When one of the "Yes", "No", "Maybe" buttons is clicked, the web component should emit the equivalent event.
- [ ] The component can be shown/hidden via a flag property passed to the component.

**Comment by rezk2ll** [comment]
@huy-ta sprint review
