### ISSUE TITLE
[TASK][Notification component] Integrate the event notification component into Calendar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#499]
#### Prerequisites

Must be done after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/529
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/537

#### Subtasks

- [ ] Choose a place in the UI to put the event notification icon button in the Calendar app.
- [ ] Configure the dav client's Authorization headers correctly.
- [ ] Adapt the component's style to the Calendar app (the component must not have a shadow DOM for this to be possible).

**Comment by rezk2ll** [comment]
@huy-ta sprint review

**Comment by renaudboyer** [comment]
Should be done in feature branch
