### ISSUE TITLE
[TASK][Notification component] Build the full event notification component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#500]
#### Prerequisites

This issue must be done after the following issues have been resolved:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/497
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/498
- https://github.com/linagora/dav-parser/issues/3

#### Subtasks

- [ ] The web component will be named something like `tcal-event-notification`.
- [ ] The web component consists of the `tcal-event-notification-popover` component (that should have previously been built) and the alarm/notification icon button in the story's design:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/27549b5b-e4ec-4c6b-8cde-5ff6eb3f8390)

- [ ] When the icon button is clicked, the popover will be displayed at the bottom of the button.
- [ ] When there are new event notifications, the icon button should have a small red badge on it:

![image.png](https://images.zenhubusercontent.com/5fbce3afa10f25d1145edfa3/301430a3-75b6-4952-9f4b-3cd70c5732f1)

- [ ] The default icon of the icon button is a bell (the svg file can be download in the design: https://www.figma.com/file/2WT5OpFSyGuCWgLNtpv7bX/Twake-Calendar). It can be customized by passing a child node to the web component.
