### ISSUE TITLE
[TASK][Notification component] Real time update for the event notifications

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#501]
#### Prerequisites

This task must be done after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/497
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/498
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/500
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/499

#### Subtasks

- [ ] Check if there is already a published event whenever there is a new event notification in the inbox.
- [ ] If not, create a new one.
- [ ] Make sure whenever there is a new event notification in the inbox, it should be updated in real time in the event notification component.
