### ISSUE TITLE
[TASK][Notification component] Real time update for event notifications

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#502]
#### Prerequisites

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/497
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/498
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/500
- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/499

#### Subtasks

- [ ] Check if there is already a published event when there is a new event notification in the inbox (when there is a new document in the `schedulingobjects` collection).
- [ ] If not, create a new one.
- [ ] Make sure the frontend listens to the event and updates the data in real time accordingly.
