### ISSUE TITLE
[TASK][Find a time - Planner view] Boostraping the planner view component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#505]
#### Prerequisites

This issue must be started after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/504

#### Subtasks

- [ ] The web component's name can be something like `tcal-planner-view`.
- [ ] The component comprises `tcal-calendar-view` and additional information (described below).
- [ ] The component will take in a list of events (the data structure/shape of the events is the same as defined in `tcal-calendar-view`) and display those events on a calendar view together with the information of who those events belong to:

_design to be updated_

- [ ] All the events emitted by `tcal-calendar-view` will also be emitted by this component (some form of event bubbling).
- [ ] The component will take in a time window (with start & end) and always display that time window in the calendar view (with some kind of highlighting effect):

_design to be updated_
