### ISSUE TITLE
[TASK][Find a time - Planner view] Integrate the planner view web component into Calendar

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#506]
#### Prerequisites

This issue must be started after:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/505

#### Subtasks

- [ ] There is a "Find a time" button right below the date & time section (see [Picture 1](#picture-1)).
- [ ] When clicking the "Find a time" button, the planner view will be displayed, showing all the available & busy time slots of all the attendees (see [Picture 2](#picture-2)).
- [ ] At the bottom of the planner view lies a section to display the attendees' corresponding colors (see [Picture 2](#picture-2)).
- [ ] The organizer can select a time by dragging in the planner view, and the selected time will be highlighted in the planner view as well (see [Picture 2](#picture-2)).
- [ ] In mobile devices, when clicking the "Find a time" button, the planner view will be opened (see [Picture 4](#picture-4)).
- [ ] In mobile devices, the planner view can be closed by clicking the arrow left icon at the top left of the screen (see [Picture 4](#picture-4)).

<h4 id="design">UI/UX Design</h4>

- <b id="picture-1">Picture 1</b>: Desktop design (Planner view is not opened)

![image](https://user-images.githubusercontent.com/24670327/105797771-2fca9880-5fc3-11eb-9802-fd2fd42d65af.png)

- <b id="pictire-2">Picture 2</b>: Desktop design (Planner view is opened)

![image](https://user-images.githubusercontent.com/24670327/105816555-0a4f8600-5fe7-11eb-9af7-a17154e3e629.png)

- <b id="picture-3">Picture 3</b>: Mobile design (Planner view is not opened)

![image](https://user-images.githubusercontent.com/24670327/105795083-d3fe1080-5fbe-11eb-899b-6d02e20cee75.png)

- <b id="picture-4">Picture 4</b>: Mobile design (Planner view is opened - Week view)

![image](https://user-images.githubusercontent.com/24670327/105816006-4df5c000-5fe6-11eb-9a70-b322c03c6d7e.png)
