### ISSUE TITLE
[TASK][Notification component] Add the logic to fetch event notifications (inbox) to the CalNotification component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#529]
#### Prerequisites

This issue must be done after the following issues have been resolved:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/500

#### Subtasks

- [ ] Pick a library for the store's implementation details
- [ ] Implement the store logic for event notifications
- [ ] Create the service & repository that fetches event notifications
- [ ] Create a hook to handle subscribing to the store and calling to the service to fetch event notifications
- [ ] In the `CalNotification` component, instead of using the fake data, pass the real data from the hook mentioned above
