### ISSUE TITLE
[TASK][Notification component] Add i18n service and the logic to handle it for the CalNotification component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#530]
#### Prerequisites

This issue must be done after the following issues have been resolved:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496

#### Subtasks

- [ ] Pick a library to handle i18n
- [ ] Build the i18n service
- [ ] The i18n service must provide a way (a method) to change locale dynamically
- [ ] Add the translations for the CalNotification component
