### ISSUE TITLE
[TASK][Notification component] Add timezone service and the logic to handle it for the CalNotification component

### ISSUE THREAD

**Issue by huy-ta** [OpenPaaS-Suite/esn-frontend-calendar#531]
#### Prerequisites

This issue must be done after the following issues have been resolved:

- https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/496

#### Subtasks

- [ ] Pick a way/library to handle timezone (Native methods or [Luxon](https://moment.github.io/luxon/))
- [ ] Build the timezone service
- [ ] The timezone service must provide a way (a method) to change timezone dynamically
- [ ] Make sure the CalNotification component displays the time in the correct timezone
